export const menuData = [{
  title:'首页',
  key:'page_index',
  path:'/',
  sections:[{
    title:'首页',
    key:'section_index',
    items:[{
      title:'系统首页',
      key:'dashboard',
      path:'/dashboard'
    },{
      title:'账户设置',
      key:'user_set',
      path:'/user-set'
    },{
      title:'登录日志',
      key:'login_log',
      path:'login-log'
    }]
  }]
},{
  title:'用户',
  key:'user',
  path:'/user',
  sections:[{
    title:'用户管理',
    key:'section_user',
    items:[{
      title:'用户列表',
      key:'user_list',
      path:'/user-list'
    },{
      title:'综合筛选',
      key:'user_filter',
      path:'/user-filter'
    },{
      title:'标签列表',
      key:'tags_list',
      path:'/tags-list'
    }]
  }]
},{
  title:'社区',
  key:'community',
  path:'/community',
  sections:[{
    title:'社区管理',
    key:'section_community',
    items:[{
      title:'小组管理',
      key:'group_manage',
      path:'/group-manage',
    },{
      title:'话题管理',
      key:'tags_manage',
      path:'/tags-manage',
    },{
      title:'评论管理',
      key:'comment_manage',
      path:'/comment-manage',
    }]
  },{
    title:'附属功能',
    key:'section_sub_funtion',
    items:[{
      title:'分类管理',
      key:'classify_manage',
      path:'/classify-manage',
    },{
      title:'违规管理',
      key:'violate_manage',
      path:'/violate-manage',
    },{
      title:'草稿箱',
      key:'draft_manage',
      path:'/draft-manage',
    }]
  }]
}]